import { CharacterConfig } from '../types';

export const CHARACTER_ROSTER: CharacterConfig[] = [
  {
    id: 'slime_replicator',
    name: '6漢肺炎',
    title: 'Ctrl + C',
    quote: '「Ctrl + v⁹⁹⁹⁹」',
    themeColor: '#84cc16',
    glowColor: 'rgba(132, 204, 22, 0.65)',
    accentColor: '#a3e635',
    baseRole: 'controller',
    stats: {
      hp: 100,
      maxHp: 100,
      speed: 310,
      attackPower: 35,
      defense: 0,
      attackRange: 120,
      attackSpeed: 2.2,
      critRate: 0.2,
      difficulty: 4,
      attackInterval: 1.4, // attacks every 1.4s
      bounceSpeed: 310,
    },
    skills: {
      primary: {
        id: 'slime_spit',
        name: 'RBD',
        keyNameP1: 'J',
        keyNameP2: '1 / [',
        cooldown: 0.35,
        energyCost: 0,
        description: '受體結合域',
        iconName: 'Sparkles',
        type: 'attack',
      },
      skill1: {
        id: 'forced_mitosis',
        name: '裂殖',
        keyNameP1: 'K',
        keyNameP2: '2 / ]',
        cooldown: 10.0,
        energyCost: 20,
        description: '觸發有絲分裂，在場上未達上限(10隻)時額外增殖出一個活性分身',
        iconName: 'Zap',
        type: 'dash',
      },
      skill2: {
        id: 'acid_slime_burst',
        name: 'RNA',
        keyNameP1: 'L',
        keyNameP2: '3 / \\',
        cooldown: 10.0,
        energyCost: 35,
        description: '周身爆發單鏈正股，擊退周圍敵方並降低其移動速度 40%！',
        iconName: 'Activity',
        type: 'aoe',
      },
      ultimate: {
        id: 'grand_hyper_fusion',
        name: '聚合',
        keyNameP1: 'Space / U',
        keyNameP2: '0 / Enter',
        cooldown: 16.0,
        energyCost: 100,
        description: '召喚場上所有同伴融合，血量暴增翻倍並震飛全場',
        iconName: 'RotateCw',
        type: 'ultimate',
      },
    },
    visual: {
      bodyColor: '#365314',
      trimColor: '#bef264',
      weaponColor: '#84cc16',
      auraColor: 'rgba(132, 204, 22, 0.5)',
      avatarEmoji: '🦠',
      shape: 'circle',
    },
  },
  {
    id: 'mlg_guy',
    name: 'MLG guy',
    title: 'Mom get the camera!!!',
    quote: 'wombo combo!!!',
    themeColor: '#22c55e',
    glowColor: 'rgba(34, 197, 94, 0.75)',
    accentColor: '#f97316',
    baseRole: 'ranged',
    stats: {
      hp: 1000,
      maxHp: 1000,
      speed: 300,
      attackPower: 90,
      defense: 0,
      attackRange: 380,
      attackSpeed: 1.5,
      critRate: 0.35,
      difficulty: 2,
      attackInterval: 1.8, // attacks every 1.8s with sniper rifle
      bounceSpeed: 310,
    },
    skills: {
      primary: {
        id: 'mlg_sniper_shot',
        name: '360狙擊槍射擊',
        keyNameP1: 'J',
        keyNameP2: '1 / [',
        cooldown: 0.5,
        energyCost: 0,
        description: '掏出重型狙擊槍打出一發超高速狙擊子彈，造成 90+ 點爆頭穿甲傷害並觸發 Hitmarker！',
        iconName: 'Crosshair',
        type: 'attack',
      },
      skill1: {
        id: 'eat_doritos',
        name: '吃多力多滋',
        keyNameP1: 'K',
        keyNameP2: '2 / ]',
        cooldown: 10.0,
        energyCost: 20,
        description: '回復 200 滴血量',
        iconName: 'Sparkles',
        type: 'buff',
      },
      skill2: {
        id: 'drink_mountain_dew',
        name: '喝激浪汽水',
        keyNameP1: 'L',
        keyNameP2: '3 / \\',
        cooldown: 10.0,
        energyCost: 40,
        description: '移動速度 20 倍持續 5 秒 撞到人扣除 50 點血量',
        iconName: 'Zap',
        type: 'buff',
      },
      ultimate: {
        id: 'mlg_360_noscope',
        name: '360° 反彈狙擊彈',
        keyNameP1: 'Space / U',
        keyNameP2: '0 / Enter',
        cooldown: 35.0,
        energyCost: 100,
        description: '【終極大招】360° 齊射 6 發高速反彈狙擊彈！每觸壁反彈一次速度激增（越反彈越快），場上存活 20 秒，打到人即造成高額傷害並消失！',
        iconName: 'Crosshair',
        type: 'ultimate',
      },
    },
    visual: {
      bodyColor: '#14532d',
      trimColor: '#f97316',
      weaponColor: '#22c55e',
      auraColor: 'rgba(34, 197, 94, 0.6)',
      avatarEmoji: '🕶️',
      shape: 'circle',
    },
  },
  {
    id: 'gordon_ramsay',
    name: '戈登·拉姆齊',
    title: '米其林評級．地獄廚神',
    quote: '這根本是生的！',
    themeColor: '#ea580c',
    glowColor: 'rgba(234, 88, 12, 0.75)',
    accentColor: '#fbbf24',
    baseRole: 'melee',
    stats: {
      hp: 1100,
      maxHp: 1100,
      speed: 310,
      attackPower: 85,
      defense: 15,
      attackRange: 70,
      attackSpeed: 2.0,
      critRate: 0.25,
      difficulty: 3,
      attackInterval: 1.2, // attacks every 1.2s with Chef Knife combo
      bounceSpeed: 315,
    },
    skills: {
      primary: {
        id: 'chef_knife_art',
        name: '主廚刀法',
        keyNameP1: 'J',
        keyNameP2: '1 / [',
        cooldown: 0.4,
        energyCost: 0,
        description: '俐落三連擊！第三擊造成小範圍扇形劈砍並施加 3 秒流血傷害（地獄火海期間附帶範圍烈焰波）。',
        iconName: 'Crosshair',
        type: 'attack',
      },
      skill1: {
        id: 'its_raw_meat',
        name: '這根本是生的！',
        keyNameP1: 'K',
        keyNameP2: '2 / ]',
        cooldown: 8.0,
        energyCost: 25,
        description: '抓起未熟透的冰凍生肉砸向指定方向，命中碎裂使周圍定身 1 秒並降低 30% 護甲持續 2.5 秒',
        iconName: 'Sparkles',
        type: 'attack',
      },
      skill2: {
        id: 'shut_it_down',
        name: '清場',
        keyNameP1: 'L',
        keyNameP2: '3 / \\',
        cooldown: 10.0,
        energyCost: 35,
        description: '引發燃氣火焰大爆炸擊飛周圍敵人，原地留下 4 秒地獄火海（每秒灼燒+減速 40%），期間普攻附帶範圍烈焰波！',
        iconName: 'Flame',
        type: 'attack',
      },
      ultimate: {
        id: 'hellfire_inferno',
        name: '地獄火海',
        keyNameP1: 'Space / U',
        keyNameP2: '0 / Enter',
        cooldown: 40.0,
        energyCost: 100,
        description: '引發全場超大範圍地獄火海大爆炸並進入暴怒烈焰狀態！移動軌跡持續產生燃燒 5 秒的地獄火海（每秒灼燒與減速 40%），期間普攻附帶範圍烈焰波！',
        iconName: 'Flame',
        type: 'ultimate',
      },
    },
    visual: {
      bodyColor: '#991b1b',
      trimColor: '#fbbf24',
      weaponColor: '#e2e8f0',
      auraColor: 'rgba(234, 88, 12, 0.65)',
      avatarEmoji: '👨‍🍳',
      shape: 'circle',
    },
  },
  {
    id: 'target_dummy',
    name: '測試假人 (Target Dummy)',
    title: '技能測試．極限傷害標靶',
    quote: '「來吧！盡情測試你的所有技能、連招與爆發大招！」',
    themeColor: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.75)',
    accentColor: '#38bdf8',
    baseRole: 'tank',
    stats: {
      hp: 999999,
      maxHp: 999999,
      speed: 0,
      attackPower: 0,
      defense: 0,
      attackRange: 0,
      attackSpeed: 0,
      critRate: 0,
      difficulty: 1,
      attackInterval: 9999,
      bounceSpeed: 0,
    },
    skills: {
      primary: {
        id: 'dummy_absorb',
        name: '抗性受擊測試',
        keyNameP1: 'J',
        keyNameP2: '1 / [',
        cooldown: 0.1,
        energyCost: 0,
        description: '吸收並記錄所有打擊傷害，即時反饋 DPS 與受擊特效。',
        iconName: 'Shield',
        type: 'defense',
      },
      skill1: {
        id: 'dummy_full_heal',
        name: '瞬間滿血重置',
        keyNameP1: 'K',
        keyNameP2: '2 / ]',
        cooldown: 1.0,
        energyCost: 0,
        description: '立即回復至 999,999 滿血狀態並重置受擊記錄。',
        iconName: 'Sparkles',
        type: 'buff',
      },
      skill2: {
        id: 'dummy_clear_effects',
        name: '淨化所有狀態',
        keyNameP1: 'L',
        keyNameP2: '3 / \\',
        cooldown: 1.0,
        energyCost: 0,
        description: '清除身上所有灼燒、流血、減速、破甲與定身狀態。',
        iconName: 'RotateCw',
        type: 'buff',
      },
      ultimate: {
        id: 'dummy_instant_energy',
        name: '全隊大招充能',
        keyNameP1: 'Space / U',
        keyNameP2: '0 / Enter',
        cooldown: 1.0,
        energyCost: 0,
        description: '立即為測試者充滿 100% 怒氣大招能量並刷新所有技能冷卻！',
        iconName: 'Zap',
        type: 'ultimate',
      },
    },
    visual: {
      bodyColor: '#1e293b',
      trimColor: '#38bdf8',
      weaponColor: '#cbd5e1',
      auraColor: 'rgba(56, 189, 248, 0.5)',
      avatarEmoji: '🎯',
      shape: 'circle',
    },
  },
];
